name: 'PR description checker'
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - labeled
      - unlabeled

jobs:
  setup-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.17.0'
      - run: go version
  check-pr-description:
    runs-on: ubuntu-latest
    steps:
      - name: Run script
        run: go run ./.github/scripts/check_pr.go
