name: 'PR description checker'
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - labeled
      - unlabeled

jobs:
  setup-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.18.0'
      - run: go version
  check-pr-description:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .github/scripts/
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.18.0'
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - run: go run main
        env:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

